version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    networks:
      - dev

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeThis
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - dev

networks:
    dev:
        driver: bridge